import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 3rem;
          }
          h3{
            font-size: 1.5rem;
          }
        `}
      </style>
      <Head>
        <title>morph</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blog, blogs, morph blog, morpg blogs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blogs'><a><li>Blogs</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>

        <h1 className={styles.title}>
          morph!
        </h1>
        <div className={styles.imageWrapper}>
          <Image className={styles.headerImg} src='/headerImg.jpg' alt='img' height={256} width={400} />
        </div>
        <p className={styles.description}>
          a noob trying to make his first blog website!
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>changing my career path</h3>
            <p>how i switched from mechanical engineering to software development</p>
          </div>
          <div className="blogItem">
            <h3>changing my career path</h3>
            <p>how i switched from mechanical engineering to software development</p>
          </div>
          <div className="blogItem">
            <h3>changing my career path</h3>
            <p>how i switched from mechanical engineering to software development</p>
          </div>
          <div className="blogItem">
            <h3>changing my career path</h3>
            <p>how i switched from mechanical engineering to software development</p>
          </div>
        </div>
      </main>
    </div>
  )
}
